source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'RegexKitLiteLib_Example' do
  pod 'RegexKitLiteLib', :path => '../'

  target 'RegexKitLiteLib_Tests' do
    inherit! :search_paths

    
  end
end
