desc "向cocoapods提交代码库"
lane :eslib do |options|
target_version = options[:version]
project        = options[:project]
path           = "#{project}.podspec"

cocoapods(
clean: true,
podfile: "./Example/Podfile"
)  # pod install 重新安装一下代码

# git add .
git_add(path: ".") 

# git commit -m 'xxx'
git_commit(path: ".", message: "提交本地代码") 

# git push origin master
push_to_git_remote 

# 自定义action
if git_tag_exists(tag: target_version)
UI.message("已经存在这个标签, 处理操作: 删除本地&远程标签#{target_version} 🚀")
remove_tag(tagName: target_version, dR:true, dL:true)
end

# git tag -a xx
add_git_tag(tag: target_version) 

# git push --tags
push_git_tags

# pod lib lint
pod_lib_lint(allow_warnings: true) 

# pod trunk push
pod_push(path: path)

end

